graph_my_playlist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('pages/', include('pages.urls')),
    path('spotify/', include('spotify.urls')),
]

pages/urls.py
from django.urls import path
from .views import login_view, callback_view, playlist_view

app_name = 'pages'

urlpatterns = [
    path('', login_view),
    path('login', login_view),
    path('callback/<str:pk>', callback_view, name='callback'),
    path('playlist/<str:id>', playlist_view, name='playlist')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Graph My Playlist</title>
    {% load static %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />
  </head>
  <body style="background-color: black; color: white">
    {% block content %} {% endblock %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/callback.html
{% extends 'base.html' %} {% block content %}

<h2 style="margin: 2rem 2rem 1rem 2rem">
  Welcome, {{display_name}}, click one of your playlists below to have it
  analyzed.
</h2>

<div
  class="row row-cols-2 row-cols-sm-3 row-cols-md-4 row-cols-lg-6 g-3"
  style="margin-left: 0.25rem; margin-right: 0.25rem"
>
  {% for name, id, image in playlist_values %}
  <div class="col">
    <div class="card text-bg-dark">
      <img
        src="{{image}}"
        class="img-fluid rounded-start"
        alt="playlist image"
      />
      <div class="card-body">
        <a
          href="{% url 'pages:playlist' id %}?user={{spotify_id}}"
          style="color: inherit; text-align: center"
        >
          <h5 class="card-title">{{name}}</h5>
        </a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

<!--  
<ol>
  <li>
    <a
      
      style="color: inherit"
    >
      {{name}}</a
    >
  </li>
</ol>   -->

{% endblock %}

templates/login.html
{% extends 'base.html' %} {% block content %}

<div
  class="container"
  style="
    display: flex;
    flex-direction: column;
    align-items: center;
    border: 2px solid #1db954;
    border-radius: 10px;
    margin-top: 10%;
    margin-bottom: 10%;
    position: relative;
  "
>
  <h2 style="margin: 2rem 2rem 0 2rem">
    Welcome to GraphMyPlaylist.com. Sign in with Spotify below and then choose
    from one of the many playlists you've made or subscribed to using your
    Spotify account. GraphMyPlaylist will then analyze your playlist and show
    you the results. Enjoy!
  </h2>
  <button
    type="button"
    onclick="logInWithSpotify()"
    style="
      background-color: #1db954;
      font-weight: bold;
      border-radius: 5px;
      height: 3rem;
      width: 50%;
      margin-top: 2rem;
      margin-bottom: 3rem;
    "
  >
    Log-in with Spotify
  </button>
  <div
    style="position: absolute; bottom: 0; left: 0; margin: 0 0 0.5rem 0.5rem"
  >
    Powered by Spotify
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="16"
      height="16"
      fill="currentColor"
      class="bi bi-spotify"
      viewBox="0 0 16 16"
    >
      <path
        d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.669 11.538a.498.498 0 0 1-.686.165c-1.879-1.147-4.243-1.407-7.028-.77a.499.499 0 0 1-.222-.973c3.048-.696 5.662-.397 7.77.892a.5.5 0 0 1 .166.686zm.979-2.178a.624.624 0 0 1-.858.205c-2.15-1.321-5.428-1.704-7.972-.932a.625.625 0 0 1-.362-1.194c2.905-.881 6.517-.454 8.986 1.063a.624.624 0 0 1 .206.858zm.084-2.268C10.154 5.56 5.9 5.419 3.438 6.166a.748.748 0 1 1-.434-1.432c2.825-.857 7.523-.692 10.492 1.07a.747.747 0 1 1-.764 1.288z"
      />
    </svg>
  </div>
</div>

<script>
  logInWithSpotify = () => {
    fetch("/spotify/get-auth-url")
      .then((response) => response.json())
      .then((data) => {
        window.location.replace(data.url);
      });
  };
</script>
{% endblock %}

templates/playlist.html
{% extends 'base.html' %} {% block content %}
<div style="position: relative; height: 1rem">
  <button
    type="button"
    class="btn btn-light"
    data-bs-toggle="offcanvas"
    data-bs-target="#offcanvasWithBothOptions"
    aria-controls="offcanvasWithBothOptions"
    style="
      position: absolute;
      right: 0;
      margin-top: 0.25rem;
      margin-right: 0.25rem;
    "
  >
    How did you determine these stats?
  </button>
</div>
<h1 style="text-align: center; margin: 2rem 0 2rem 0">Your Playlist's Stats</h1>
<!--<ul>
  <li>Acousticness: {{acousticness}}</li>
  <li>Danceability: {{danceability}}</li>
  <li>Energy: {{energy}}</li>
  <li>Duration: {{duration}}</li>
  <li>Tempo: {{tempo}} in bpm</li>
  <li>Valence: {{valence}}</li>
</ul>
-->
<div id="valenceDiv" class="container" style="margin: auto">
  <svg viewbox="0 0 500 75" id="valenceSVG"></svg>
</div>
<div id="energyDiv" class="container" style="margin: auto">
  <svg viewbox="0 0 500 75" id="energySVG"></svg>
</div>
<div id="danceDiv" class="container" style="margin: auto">
  <svg viewbox="0 0 500 75" id="danceSVG"></svg>
</div>
<div id="acousticnessDiv" class="container" style="margin: auto">
  <svg viewbox="0 0 500 75" id="acousticSVG"></svg>
</div>

<!--
<div id="popularityDiv" class="container" style="margin: auto">
  <svg viewbox="0 0 500 75" id="popularitySVG"></svg>
</div>

<div id="genreDiv" class="container" style="margin: auto">
  <svg viewbox="0 0 500 500" id="genreSVG"></svg>
</div>
-->

<div
  class="offcanvas offcanvas-end text-bg-dark"
  data-bs-scroll="true"
  tabindex="-1"
  id="offcanvasWithBothOptions"
  aria-labelledby="offcanvasWithBOthOptionsLabel"
>
  <div class="offcanvas-header">
    <button
      type="button"
      class="btn-close btn-close-white"
      data-bs-dismiss="offcanvas"
      aria-label="Close"
    ></button>
    <h5 class="offcanvas-title" id="offcanvasWithBothOptionsLabel">
      How did you determine these stats?
    </h5>
  </div>
  <div class="offcanvas-body">
    <p>
      Spotify provides audio information for each song on its platform.
      GraphMyPlaylist.com finds that information for each song in your playlist
      and then finds the average value for the entire playlist. A description of
      each metric from Spotify is provided below.<br /><br />
      Valence (or mood) - A measure from 0.0 to 1.0 describing the musical
      positiveness conveyed by a track. Tracks with high valence sound more
      positive (e.g. happy, cheerful, euphoric), while tracks with low valence
      sound more negative (e.g. sad, depressed, angry).<br /><br />
      Energy - Energy is a measure from 0.0 to 1.0 and represents a perceptual
      measure of intensity and activity. Typically, energetic tracks feel fast,
      loud, and noisy. For example, death metal has high energy, while a Bach
      prelude scores low on the scale. Perceptual features contributing to this
      attribute include dynamic range, perceived loudness, timbre, onset rate,
      and general entropy. <br /><br />
      Danceability - Danceability describes how suitable a track is for dancing
      based on a combination of musical elements including tempo, rhythm
      stability, beat strength, and overall regularity. A value of 0.0 is least
      danceable and 1.0 is most danceable.<br /><br />
      Acousticness - A confidence measure from 0.0 to 1.0 of whether the track
      is acoustic. 1.0 represents high confidence the track is acoustic.
      <br /><br />
      <!--Popularity - The popularity of a track is a value between 0 and 100, with
      100 being the most popular. The popularity is calculated by algorithm and
      is based, in the most part, on the total number of plays the track has had
      and how recent those plays are.-->
    </p>
  </div>
</div>
<!--{{genre_names}}-->

<script src="https://d3js.org/d3.v7.min.js"></script>

<script type="text/javascript">
  /*Create line graph for danceability*/
  let danceabilityPoint = "{{danceability}}" * 350 + 50;

  let xDance = d3
    .scalePoint()
    .domain(["Least Danceable", "Most Danceable"])
    .range([50, 400]);

  let xAxisDance = d3.axisBottom(xDance);

  d3.select("#danceSVG")
    .append("g")
    .attr("transform", "translate(0,50)")
    .call(xAxisDance);

  d3.select("#danceSVG")
    .append("circle")
    .attr("cx", danceabilityPoint)
    .attr("cy", 50)
    .attr("r", 5)
    .attr("fill", "white");

  d3.select("#danceSVG")
    .append("text")
    .attr("x", 200)
    .attr("y", 20)
    .text("Danceability")
    .style("fill", "white");

  /*Acousticness*/
  let AcousticnessPoint = "{{acousticness}}" * 350 + 50;

  let xAcoustic = d3
    .scalePoint()
    .domain(["Not Acoustic", "Very Acoustic"])
    .range([50, 400]);

  let xAxisAcoustic = d3.axisBottom(xAcoustic);

  d3.select("#acousticSVG")
    .append("g")
    .attr("transform", "translate(0,50)")
    .call(xAxisAcoustic);

  d3.select("#acousticSVG")
    .append("circle")
    .attr("cx", AcousticnessPoint)
    .attr("cy", 50)
    .attr("r", 5)
    .attr("fill", "white");

  d3.select("#acousticSVG")
    .append("text")
    .attr("x", 200)
    .attr("y", 20)
    .text("Acousticness")
    .style("fill", "white");

  /*Energy*/
  let EnergyPoint = "{{energy}}" * 350 + 50;

  let xEnergy = d3
    .scalePoint()
    .domain(["Low Energy", "High Energy"])
    .range([50, 400]);

  let xAxisEnergy = d3.axisBottom(xEnergy);

  d3.select("#energySVG")
    .append("g")
    .attr("transform", "translate(0,50)")
    .call(xAxisEnergy);

  d3.select("#energySVG")
    .append("circle")
    .attr("cx", EnergyPoint)
    .attr("cy", 50)
    .attr("r", 5)
    .attr("fill", "white");

  d3.select("#energySVG")
    .append("text")
    .attr("x", 200)
    .attr("y", 20)
    .text("Energy")
    .style("fill", "white");

  /*Valence*/
  let valencePoint = "{{valence}}" * 350 + 50;

  let xValence = d3
    .scalePoint()
    .domain(["Sad/Depressed", "Happy/Cheerful"])
    .range([50, 400]);

  let xAxisValence = d3.axisBottom(xValence);

  d3.select("#valenceSVG")
    .append("g")
    .attr("transform", "translate(0,50)")
    .call(xAxisValence);

  d3.select("#valenceSVG")
    .append("circle")
    .attr("cx", valencePoint)
    .attr("cy", 50)
    .attr("r", 5)
    .attr("fill", "white");

  d3.select("#valenceSVG")
    .append("text")
    .attr("x", 200)
    .attr("y", 20)
    .text("Mood")
    .style("fill", "white");
  /*
  Popularity
  let popularityPoint = "{{popularity}}" * 3.5 + 50;

  let xPopularity = d3
    .scalePoint()
    .domain(["Least Popular", "Most Popular"])
    .range([50, 400]);

  let xAxisPopularity = d3.axisBottom(xPopularity);

  d3.select("#popularitySVG")
    .append("g")
    .attr("transform", "translate(0,50)")
    .call(xAxisPopularity);

  d3.select("#popularitySVG")
    .append("circle")
    .attr("cx", popularityPoint)
    .attr("cy", 50)
    .attr("r", 5)
    .attr("fill", "white");

  d3.select("#popularitySVG")
    .append("text")
    .attr("x", 200)
    .attr("y", 20)
    .text("Popularity")
    .style("fill", "white");
  */
  /*genres*/
  /*
  let genres = JSON.parse("{{genre_names}}");
  let genreCount = JSON.parse("{{genre_count}}");
  let tenGenres = genres.slice(0, 10);
  let tenGenreCount = genreCount.slice(0, 10);
  console.log(tenGenres);
  console.log(tenGenreCount);

  //x axis
  const xGenre = d3.scaleBand().range([50, 450]).domain(tenGenres).padding(0.2);

  d3.select("#genreSVG")
    .append("g")
    .attr("transform", "translate(0,450)")
    .call(d3.axisBottom(xGenre))
    .selectAll("text")
    .attr("transform", "translate(-10,0)rotate(-45)")
    .style("text-anchor", "end");
  //y axis
  const y = d3
    .scaleLinear()
    .domain([0, tenGenreCount[0] + 1])
    .range([450, 0]);

  d3.select("#genreSVG").append("g").call(d3.axisLeft(y));
  
  d3.select("#genreSVG")
    .data(tenGenreCount)
    .join("rect")
    .attr("x", (d, i) => i * 30)
    .attr("y", 450)
    .attr("width", xGenre.bandwidth())
    .attr("height", (d) => {
      return (d / 450) * 100;
    })
    .attr("fill", "white");
    */
</script>

{% endblock %}